name: Node.js Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Setup Node.js
         uses: actions/setup-node@v3
       - name: Install Dependencies
         run: npm install
       - name: Deploy to Azure App Service
         uses: azure/webapps-deploy@v3
         with:
          app-name: Node-test-011
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .  # Adjust this path based on your build output
