name: Node.js Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
  deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Deploy to Azure App Service
         uses: azure/webapps-deploy@v3
         with:
          app-name: Node-test-011
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .  # Adjust this path based on your build output
          
       - name: Start
         run: |
           npm install
           node /app.js
